"""add_content_extraction_fields

Revision ID: 94422d01d65b
Revises: eb3bbba5a53b
Create Date: 2025-07-04 00:15:01.975473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '94422d01d65b'
down_revision: Union[str, None] = 'eb3bbba5a53b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('articles', sa.Column('published_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_articles_title'), 'articles', ['title'], unique=False)
    op.drop_column('articles', 'summary')
    op.drop_column('articles', 'created_at')
    op.drop_column('articles', 'published')
    op.add_column('feeds', sa.Column('title', sa.String(), nullable=True))
    op.add_column('feeds', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('feeds', sa.Column('link', sa.String(), nullable=True))
    op.add_column('feeds', sa.Column('published_date', sa.DateTime(), nullable=True))
    op.add_column('feeds', sa.Column('source', sa.String(), nullable=True))
    op.add_column('feeds', sa.Column('content', sa.Text(), nullable=True))
    op.add_column('feeds', sa.Column('content_html', sa.Text(), nullable=True))
    op.add_column('feeds', sa.Column('author', sa.String(), nullable=True))
    op.add_column('feeds', sa.Column('image_urls', sa.JSON(), nullable=True))
    op.add_column('feeds', sa.Column('keywords', sa.JSON(), nullable=True))
    op.add_column('feeds', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('feeds', sa.Column('extracted_by', sa.String(), nullable=True))
    op.add_column('feeds', sa.Column('extraction_time', sa.DateTime(), nullable=True))
    op.add_column('feeds', sa.Column('extraction_success', sa.Boolean(), nullable=True))
    op.add_column('feeds', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('feeds', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint('feeds_url_key', 'feeds', type_='unique')
    op.drop_index('ix_feeds_name', table_name='feeds')
    op.create_index(op.f('ix_feeds_language'), 'feeds', ['language'], unique=False)
    op.create_index(op.f('ix_feeds_link'), 'feeds', ['link'], unique=True)
    op.create_index(op.f('ix_feeds_region'), 'feeds', ['region'], unique=False)
    op.create_index(op.f('ix_feeds_source'), 'feeds', ['source'], unique=False)
    op.create_index(op.f('ix_feeds_state'), 'feeds', ['state'], unique=False)
    op.create_index(op.f('ix_feeds_title'), 'feeds', ['title'], unique=False)
    op.drop_column('feeds', 'name')
    op.drop_column('feeds', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feeds', sa.Column('url', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.add_column('feeds', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_feeds_title'), table_name='feeds')
    op.drop_index(op.f('ix_feeds_state'), table_name='feeds')
    op.drop_index(op.f('ix_feeds_source'), table_name='feeds')
    op.drop_index(op.f('ix_feeds_region'), table_name='feeds')
    op.drop_index(op.f('ix_feeds_link'), table_name='feeds')
    op.drop_index(op.f('ix_feeds_language'), table_name='feeds')
    op.create_index('ix_feeds_name', 'feeds', ['name'], unique=True)
    op.create_unique_constraint('feeds_url_key', 'feeds', ['url'])
    op.drop_column('feeds', 'updated_at')
    op.drop_column('feeds', 'created_at')
    op.drop_column('feeds', 'extraction_success')
    op.drop_column('feeds', 'extraction_time')
    op.drop_column('feeds', 'extracted_by')
    op.drop_column('feeds', 'summary')
    op.drop_column('feeds', 'keywords')
    op.drop_column('feeds', 'image_urls')
    op.drop_column('feeds', 'author')
    op.drop_column('feeds', 'content_html')
    op.drop_column('feeds', 'content')
    op.drop_column('feeds', 'source')
    op.drop_column('feeds', 'published_date')
    op.drop_column('feeds', 'link')
    op.drop_column('feeds', 'description')
    op.drop_column('feeds', 'title')
    op.add_column('articles', sa.Column('published', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('articles', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('articles', sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_articles_title'), table_name='articles')
    op.drop_column('articles', 'published_date')
    op.drop_column('articles', 'description')
    # ### end Alembic commands ### 